data:
  DATA_DIR: ~/data/VOC2012/VOCdevkit/VOC2012/Pointer
  NUM_CLASSES: 22
  NUM_CHANNELS: 3
  DATA_SET: VOC2012
  SIZE: 5464

train:
  PRETRAINED: true
  ALPHA: 10
  RANDOM_SEED: 19260817
  LR: 0.001
  BATCH_SIZE: 64
  NUM_EPOCH: 40
  SAVE_PERIOD: 1
  WEIGHT_DIR: weights
  WORKERS: 0,1,2,3
  TASK: offset
  SNAPSHOT: net03_seg_12
  MILESTONE: 5
  GAMMA: 0.83
